### ISSUE TITLE
204 no contents break _everything_

### ISSUE THREAD

**Issue by ParamagicDev** [ParamagicDev/mrujs#106]
#### Expected Behavior

204 no contents should request the current page

#### Actual Behaviour

204s do nothing.

#### Proposed Fix

Use morphdom to request the current page and then morph the response

**Comment by manuelreis** [comment]
@ParamagicDev do you suggest any workaround? Trying to create a link to Devise's sign out here.

**Comment by ParamagicDev** [comment]
A.) listen for `ajax:success`, check `event.detail.status == 204` and then issue a window.location.reload() to force a manual reload. (Not Recommended)
B.) The other options is to override the default devise behavior and send back a redirect to an actual location.

I believe this _should_ work for ya. 

https://gist.github.com/ParamagicDev/8f93a71d3498265cb84ce2d665b9955a
