### ISSUE TITLE
Used with Turbo cause "Uncaught TypeError: Cannot redefine property: submitter" on old browser

### ISSUE THREAD

**Issue by jitingcn** [ParamagicDev/mrujs#113]
#### Expected Behaviour
no error
#### Actual Behaviour
```
Uncaught TypeError: Cannot redefine property: submitter
    at Function.defineProperty (<anonymous>)
    at turbo.es2017-esm.js:39
```
#### Steps to Reproduce
in application.js
```
import mrujs from "mrujs"
import { Turbo } from "@hotwired/turbo-rails"
window.Turbo = Turbo
mrujs.start()
```
#### environment
rails 6.1.4
vite ruby 
Test on Chrome Android 78 which is no native support SubmitEvent API

I believe this issue is caused by repeated execution of the polyfill twice.  
Object.defineProperty will set `writable: false, enumerable: false, configurable: false` by default.

**Comment by ParamagicDev** [comment]
Thank you. I'll add another check to see if the polyfill already exists.

**Comment by ParamagicDev** [comment]
@jitingcn Feel free to re-open this if `0.4.12` doesnt solve this issue.

Import order will matter for the time being assuming https://github.com/hotwired/turbo/pull/380 will eventually get merged (hopefully)

So:

```js
import * as Turbo from "@hotwired/turbo"
import mrujs from "mrujs"
```

is the recommended order at this time.
