### ISSUE TITLE
Type declarations aren't being emitted

### ISSUE THREAD

**Issue by ohmree** [ParamagicDev/mrujs#139]
#### Expected Behaviour
For type declarations to be emitted to `dist/`.

#### Actual Behaviour
Only transpiled source code is emitted.

#### Steps to Reproduce
Run `yarn build` in the project root.

#### Repo (if possible)
https://github.com/ohmree/mrujs

I think this issue has to do with [this section of the typescript plugin's readme](https://github.com/rollup/plugins/tree/master/packages/typescript/#declaration-output-with-outputfile).
In my fork (linked above) I've tried to fix it and managed to get rollup to output declarations correctly for the root project, but for `plugins/` the nesting is still wrong.

One thing that did eliminate the nesting for the plugins dir was to mess with `rootDir` in both the plugins project and the root one (I think, can't remember exactly what I did but it shouldn't be hard to reproduce).
That makes the build fail because `/plugins/` references `/src/types.ts` but the declarations are emitted correctly.

**Comment by ParamagicDev** [comment]
Doh...was just encountering this today as I finally had a chance to work on a personal project using Mrujs and noticed the warning. I'll see if I can get a fix up tomorrow. Seems fairly straight forward. Thank you 🙏🏻
