### ISSUE TITLE
there was an error with mrujs.confirm

### ISSUE THREAD

**Issue by karn18** [ParamagicDev/mrujs#144]
#### Expected Behaviour
Should show confirm dialog after clicked destroy button

#### Actual Behaviour
It shows an error on console
`there was an error with mrujs.confirm`

![Screenshot from 2021-10-14 14-38-30](https://user-images.githubusercontent.com/1924433/137273010-ebfcb6c1-44fe-4203-bd42-a14f41c141bf.png)

#### Steps to Reproduce
- create new blogs
- try to delete one of theme

**Comment by karn18** [comment]
After trying to call `window.confirm("hello")` on inspector console, It throws error `Uncaught InternalError: too much recursion`

![Screenshot from 2021-10-16 12-48-48](https://user-images.githubusercontent.com/1924433/137575512-52dd6cf0-522b-45ef-b72a-421d55be1a97.png)

**Comment by ParamagicDev** [comment]
Do you have a repo I could look at? This looks like something is overriding window.confirm.

**Comment by karn18** [comment]
The repo is here !!!

[https://github.com/karn18/abc](https://github.com/karn18/abc)

**Comment by ParamagicDev** [comment]
@karn18 is this still an issue in the latest v0.8.3? Apologies for leaving you hanging this long.

**Comment by karn18** [comment]
> @karn18 is this still an issue in the latest v0.8.3? Apologies for leaving you hanging this long.

@ParamagicDev Now it works well after update to latest version. Thank you.
