### ISSUE TITLE
Typescript type definition problem with `mrujs.start()`

### ISSUE THREAD

**Issue by dnamsons** [ParamagicDev/mrujs#164]
#### Expected Behaviour

Using Typescript, the getting started guide should work

From the [documentation](https://mrujs.com/tutorials/getting-started#1-install-mrujs)

```ts
import mrujs from 'mrujs'

mrujs.start()
```

#### Actual Behaviour

Typescript throws a warning `Property 'start' does not exist on type 'typeof import("/node_modules/mrujs/dist/types")'`

#### Steps to Reproduce

Just import the library and try to invoke `start()` on it

**Comment by ParamagicDev** [comment]
@dnamsons thank you for the report! I have been made aware of this and hoping to have a fix in the next release!

**Comment by ParamagicDev** [comment]
@dnamsons give 0.6.1 a whirl. Type definitions should be fixed.
