### ISSUE TITLE
Cannot find module 'mrujs/plugins' or its corresponding type declarations.

### ISSUE THREAD

**Issue by grncdr** [ParamagicDev/mrujs#176]
#### Expected Behaviour

TypeScript can find `mrujs/plugins`

#### Actual Behaviour

if I write `import {MrujsTurbo} from 'mrujs/plugins'` TypeScript shows the error `Cannot find module 'mrujs/plugins' or its corresponding type declarations.`.

Webpack seems to find the module just fine.

#### Steps to Reproduce

Create a project that uses TypeScript and mrujs. Try and import from 'mrujs/plugins'

#### Repo (if possible)

https://github.com/grncdr/mrujs-repro

The above repo is using the same version of TypeScript and tsconfig settings as my actual project, but I've been unable to make the import work by upgrading or changing any of the settings there.

**Comment by ParamagicDev** [comment]
@grncdr Give me a few days for this. I know where the issue comes from (typescript most likely doesnt read import maps)

its gonna take some refactoring but I'll get this fixed.

**Comment by ParamagicDev** [comment]
I believe this is fixed in 0.8.3, feel free to reopen if it isnt.
