### ISSUE TITLE
mrujs website flashes when loading

### ISSUE THREAD

**Issue by nachiket87** [ParamagicDev/mrujs#181]
#### Expected Behaviour

Should not flash unstyled content before loading.

#### Actual Behaviour

![Screen-Recording-2022-01-28-at-1 57 23-PM](https://user-images.githubusercontent.com/33430835/151605958-33be4f7a-af06-423b-b905-1feb77260fff.gif)

#### Steps to Reproduce

visit https://www.mrujs.com

#### Notes

On a decent internet connection and only occurs on mrujs website.

**Comment by ParamagicDev** [comment]
Was playing around with some loading stuff. Check it now. Should be better :)
