### ISSUE TITLE
What to do about .js.erb

### ISSUE THREAD

**Issue by leastbad** [ParamagicDev/mrujs#4]
According to https://m.patrikonrails.com/a-definitive-guide-to-railss-unobtrusive-javascript-adapter-ef13bd047fff

...when a developer uses `redirect_to` in a controller action, the client receives Turbolinks commands in raw JS:

```rb
# app/controllers/users_controller.rb
class UserController < ApplicationController
  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end
end
```
```js
Turbolinks.clearCache()
Turbolinks.visit("http://web.dev/users",{"action":"replace"})
```

This may or may not be modified by the inclusion of `turbolinks-rails` in the project:

https://github.com/turbolinks/turbolinks-rails

It seems like this project might need to include a sidecar gem called `mrujs-rails` that duplicates the functionality of the above, except by sending JSON to the client. The real security issue was always generating the raw JS on the server.

Update:

It all comes down to this Concern:

https://github.com/turbolinks/turbolinks-rails/blob/master/lib/turbolinks/redirection.rb

---

Following the thought progression, here... it seems reasonable to assume that this is where https://github.com/jorgemanrubia/turbolinks_render comes into the picture via https://medium.com/@jmanrubia/escaping-the-spa-rabbit-hole-with-turbolinks-903f942bf52c

**Comment by ParamagicDev** [comment]
From our messages:

I think perhaps we may be able to avoid a JSON payload by sending along a header in the response like: 

```
"MRUJS_URL" = "/url"
"MRUJS_ACTION" = "replace"
```

Which could then be executed by `mrujs` on `ajax:complete` if Turbo / Turbolinks is defined. and obviously we'll fill in the appropriate headers for Turbolinks as well.

**Comment by ParamagicDev** [comment]
Headers dont persist. XmlHttpRequest could not follow redirects, fetch can. This is solved. Woo 🥳
