### ISSUE TITLE
Provide direct access to response body from within events

### ISSUE THREAD

**Issue by existentialmutt** [ParamagicDev/mrujs#43]
#### Describe Problem
Maybe I just need to get better with fetch, but after catching an ajax:success event I fumbled with jumping through async hoops to get to the body content.  Finally settled on `event.detail.response.json().then(operations => CableReady.perform(operations))` which I guess isn't that awful but took me a few tries and some digging through fetch docs to get there.

#### Suggest Solution
I'd love it if `event.detail` provided a responseBody property (or function) that provides direct access to the response body content as a string.

**Comment by ParamagicDev** [comment]
Oh right! So fetchRequest will be the place for this stuff. Right now it provides `responseHtml` but I'll look into adding `responseJson`

**Comment by existentialmutt** [comment]
Love it!  If `responseHtml` is available now where should I look for it? `event.detail.fetchRequest.responseHtml` is coming back undefined...

<img width="1059" alt="CableCarMessages" src="https://user-images.githubusercontent.com/90793/121789520-a8ae4380-cba4-11eb-98cc-b973e5cd2178.png">

**Comment by ParamagicDev** [comment]
@existentialmutt Doh! FetchRequest, FetchResponse, so close!

`await event.detail.fetchResponse.responseHtml`

Also of note, this returns a promise so it has to be async / await or `.then(() => )`

**Comment by existentialmutt** [comment]
lol that makes a lot more sense

**Comment by ParamagicDev** [comment]
@existentialmutt I'm gonna close this, im happy to reopen if you have any additional thoughts on this.
