### ISSUE TITLE
How to deal with removed attributes

### ISSUE THREAD

**Issue by ParamagicDev** [ParamagicDev/mrujs#58]
The mutationObserver now properly checks for changed attributes, but what happens if attributes are removed? Should they be rechecked for their validity and have their event listeners removed? If so, how do we make this happen? Do we create a `Set` of all watched nodes and run through them and make sure theyre correct? this is an...interesting...problem to say the least.

Perhaps another filter could be added to the [src/utils/dom.ts](https://github.com/ParamagicDev/mrujs/blob/main/src/utils/dom.ts) to check the validity of the node[s] whos attributes were removed?

**Comment by existentialmutt** [comment]
lol, I noticed this behavior when working on https://github.com/ParamagicDev/mrujs/pull/66

Went to log the issue and I wound up here.

Would it be possible to add code to the various observerCallback functions that removes the behaviors if the node doesn't match the designated attributes?

e.g. in method.ts:

```typescript
  observerCallback (nodeList: Node[]): void {
    nodeList.forEach((node) => {
      if (match(node, window.mrujs.querySelectors.linkClickSelector)) {
        node.addEventListener('click', this.handle)
      } else {
       node.removeEventListener('click', this.handle)
     }

    // ...

  }
```

**Comment by ParamagicDev** [comment]
This may not be the worst way to handle it....I know me and @leastbad have been mulling over "in what scenario would someone ever do this?"

**Comment by leastbad** [comment]
Just to throw an idea on the pile:

You could introduce a method that people could call which would fully de-mrujs an element. This would allow you to sleep well at night while Officially Not Worrying about people randomly disabling parts of an mrujs-blessed element. Programmatically removing the `data-remote` attribute is just such a weird way to solve a problem.

**Comment by ParamagicDev** [comment]
Hmmm....this seems the most sane. Allow you to remove certain pieces of functionality via JS...I like it!

**Comment by existentialmutt** [comment]
I agree this is a weird case to design for- I've certainly never done it in all my years of working with OG UJS.  A de-mrujs method sounds good to me.

**Comment by ParamagicDev** [comment]
im just gonna leave it alone until someone can come up with a compelling use case. Ive never had this come up before. Marking as closed unless someone can provide a real life example.

**Comment by leastbad** [comment]
![giphy](https://user-images.githubusercontent.com/38150464/124851792-347f7980-df71-11eb-82a6-f888af6ab464.gif)

**Comment by ParamagicDev** [comment]
![YEET!](https://tenor.com/bf63y.gif)

**Comment by ParamagicDev** [comment]
![YEET](https://giphy.com/gifs/cartoonhangover-upvote-yeet-costume-quest-5PhDdJQd2yG1MvHzJ6)
