### ISSUE TITLE
Should successful form submissions be required to redirect?

### ISSUE THREAD

**Issue by ParamagicDev** [ParamagicDev/mrujs#76]
Long story short, successful form submissions requires the form to redirect the user. Im not sure this is technically necessary.

Happy to hear other peoples feelings on this matter. The code at this point is mostly a hold-over from Turbo.

## Turbo code

https://github.com/hotwired/turbo/blob/537093ba1b037b49916c4ff04b50bdd30611f6af/src/core/drive/form_submission.ts#L140-L142

## Mrujs code

https://github.com/ParamagicDev/mrujs/blob/8441e6d40bfaf8b594020be6c507a5279bd7b65a/src/navigationAdapter.ts#L72-L75

Any discussion around this would be super helpful if its better to just morph anything that doesnt redirect instead of just >400 status codes. This would also mean you dont _need_ to set a status for failed form submissions (although you probably should)

**Comment by SgtPooki** [comment]
You should check out https://en.wikipedia.org/wiki/Post/Redirect/Get. This pattern is very common, highly recommended, and fairly easy to implement.

**Comment by ParamagicDev** [comment]
@SgtPooki im not sure I understand what's being proposed here. So yes I should leave the requirement to make users redirect on successful form submissions?

I do understand the 303 header, there's a lengthy discussion here and I don't plan to make it the default for Mrujs until rails makes it the default. I plan to have a config option to turn on / off masking a HTTP VERB other than get / post.

https://github.com/hotwired/turbo/issues/84

**Comment by existentialmutt** [comment]
I read that article as “don’t trust devs to prevent double submission bugs so introduce guardrails at the framework level.”

Maybe this is Turbo’s motivation for that requirement?  I’ve honestly never understood it and found it kind of annoying, but if it helps guide newer devs to the right pattern I could get on board with keeping it.

**Comment by ParamagicDev** [comment]
Closing for now. If someone has any other illuminating pieces of advice, feel free to reopen.
