### ISSUE TITLE
Successful Form submit behavior is inconsistent between Turbo and Turbolinks (what should it be?)

### ISSUE THREAD

**Issue by existentialmutt** [ParamagicDev/mrujs#81]
Hey Konnor, I've been so pre-occupied with cable_car I realized mrujs is doing some cool things with remote html forms and I wanted to get clear on exactly how they work.  While tinkering around with a simple scaffold I noticed different behavior depending on whether I have turbo or turbolinks enabled and that seems off.

#### Expected Behaviour
Turbo and Turbolinks should have consistent behavior for remote form submissions.

#### Actual Behaviour
When using Turbolinks: browser follows the redirect with a non-turbolinks (i.e. whole page load) navigation.

When using Turbo: nothing happens

#### Steps to Reproduce
Start up the app in the repo provided and go to http://localhost:3000 .  Fill out both fields in the form and hit submit.

Switch between using Turbo and Turbolinks by editing app/javascript/application.js

#### Repo (if possible)

https://github.com/existentialmutt/mrujs_sandbox

#### Other notes

I should add that unsuccessful form submissions work in both cases.  The page is updated in-place with the HTML from the response.  That's really cool!

I'd really love to know what the intended behavior should be.  Coming from OG UJS where everything needs to be handled manually I'm not quite sure what to expect.

**Comment by ParamagicDev** [comment]
what version of UJS are you using? I see `0.3.0-beta.25` in the `package.json` im not sure why it doesnt default to a higher install, but the latest version of `mrujs` is `0.3.0-beta.31`, perhaps when I changed my changelog generator it changed the way tags are produced? anyways, im gonna release `0.3.1` so this wont be an issue moving forward.
