### ISSUE TITLE
Compatibility methods missing

### ISSUE THREAD

**Issue by drnic** [ParamagicDev/mrujs#99]
I'm using some `@rails/ujs` methods that might be missing or need docs for compatibility to switch over to `mrujs`:

* `Rails.fire`
* `Rails.confirm` - I see this in my code base but I don't think its used

The following come from https://github.com/kirillplatonov/shopify-hotwire-sample/blob/910a2216dd61a5e52628e155901a42d185d1cf92/app/javascript/packs/application.js#L11-L17
* `Rails.delegate`
* `Rails.linkDisableSelector` -- oops, found it https://github.com/ParamagicDev/mrujs/search?q=linkDisableSelector
* `Rails.buttonDisableSelector`
* `Rails.formSubmitSelector`

My code base also uses `Rails.ajax` but AFAIK I need to port that to `fetch` right?

**Comment by ParamagicDev** [comment]
Thank you @drnic .

`Rails.confirm` exists. https://github.com/ParamagicDev/mrujs/blob/daf79a66be77f4d39a9268aeb3a83e1ed2037447/src/mrujs.ts#L152-L154

`Rails.xSelector` are all under `Rails.config.querySelectors.xSelector`

`Rails.ajax` is deprecated and is now `Rails.fetch` which uses the native fetch API

`Rails.fire` does not exist. I'll have to see about that one. I have an internal dispatch call which is probably similar.
`Rails.delegate` does not exist. I'll check and see if this is worth implementing.
